# Generated by Django 3.0.8 on 2020-07-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='user_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
