# Generated by Django 3.0.8 on 2020-08-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_pic',
            field=models.ImageField(default='profile1.png', upload_to=''),
        ),
    ]
