# Generated by Django 3.0.8 on 2020-08-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200826_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
