# Generated by Django 3.0.8 on 2020-08-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='qrcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('code', models.ImageField(upload_to='images/qrcodes')),
            ],
        ),
    ]
