# Generated by Django 3.0.8 on 2020-08-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='code',
            field=models.ImageField(upload_to=''),
        ),
    ]
